language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get -y install libblas3 liblapack3 python-setuptools
  - wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/gcc-5-base_5.4.0-6ubuntu1~16.04.4_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb
  - sudo dpkg -i gcc-5-base_5.4.0-6ubuntu1~16.04.4_amd64.deb
  - sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb
install:
  - pip install --upgrade pip
  - pip install pytest --upgrade
  - pip install -r requirements.txt
# command to run tests
cache: pip
script:
  - pip install -e .
  - python -m  pytest tests/
   # or py.test for Python versions 3.5 and below